CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    manager_id BIGINT NULL,
    max_absent_employees INTEGER NOT NULL,
    CONSTRAINT uk_department_name UNIQUE (name),
    CONSTRAINT ck_department_max_absent CHECK (max_absent_employees > 0)
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(140) NOT NULL,
    email VARCHAR(180) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    department_id BIGINT NOT NULL,
    annual_leave_days INTEGER NOT NULL,
    available_leave_days INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_employee_email UNIQUE (email),
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT ck_employee_role CHECK (role IN ('EMPLOYEE', 'MANAGER', 'ADMIN')),
    CONSTRAINT ck_employee_leave_days CHECK (annual_leave_days >= 0 AND available_leave_days >= 0)
);

ALTER TABLE departments
    ADD CONSTRAINT fk_department_manager FOREIGN KEY (manager_id) REFERENCES employees(id);

CREATE TABLE leave_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL,
    requires_attachment BOOLEAN NOT NULL,
    paid BOOLEAN NOT NULL,
    CONSTRAINT uk_leave_type_name UNIQUE (name),
    CONSTRAINT uk_leave_type_code UNIQUE (code)
);

CREATE TABLE leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    leave_type_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    working_days INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason VARCHAR(800),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_request_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_request_leave_type FOREIGN KEY (leave_type_id) REFERENCES leave_types(id),
    CONSTRAINT ck_request_period CHECK (end_date >= start_date),
    CONSTRAINT ck_request_working_days CHECK (working_days > 0),
    CONSTRAINT ck_request_status CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE leave_workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_request_id BIGINT NOT NULL,
    changed_by_id BIGINT NOT NULL,
    old_status VARCHAR(20),
    current_status VARCHAR(20) NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    comment VARCHAR(1000),
    CONSTRAINT fk_workflow_request FOREIGN KEY (leave_request_id) REFERENCES leave_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_workflow_employee FOREIGN KEY (changed_by_id) REFERENCES employees(id)
);

CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_request_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    file_size BIGINT NOT NULL,
    file_path VARCHAR(600) NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_attachment_request FOREIGN KEY (leave_request_id) REFERENCES leave_requests(id) ON DELETE CASCADE
);

CREATE INDEX idx_request_employee ON leave_requests(employee_id);
CREATE INDEX idx_request_status ON leave_requests(status);
CREATE INDEX idx_request_period ON leave_requests(start_date, end_date);
CREATE INDEX idx_workflow_request ON leave_workflows(leave_request_id);
CREATE INDEX idx_attachment_request ON attachments(leave_request_id);
