import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { Department, Employee, LeaveType, Role } from '../../core/models';

const imports=[ReactiveFormsModule,MatDialogModule,MatButtonModule,MatCheckboxModule,MatFormFieldModule,MatInputModule,MatSelectModule];

@Component({selector:'app-employee-dialog',imports,template:`<h2 mat-dialog-title>{{data.item?'Modifica utilizatorul':'Utilizator nou'}}</h2><mat-dialog-content><form [formGroup]="form" class="grid"><mat-form-field appearance="outline" class="full"><mat-label>Nume complet</mat-label><input matInput formControlName="name"/></mat-form-field><mat-form-field appearance="outline" class="full"><mat-label>Email</mat-label><input matInput type="email" formControlName="email"/></mat-form-field><mat-form-field appearance="outline" class="full"><mat-label>{{data.item?'Parola noua (optional)':'Parola'}}</mat-label><input matInput type="password" formControlName="password"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Rol</mat-label><mat-select formControlName="role"><mat-option value="EMPLOYEE">Angajat</mat-option><mat-option value="MANAGER">Manager</mat-option><mat-option value="ADMIN">Administrator</mat-option></mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Departament</mat-label><mat-select formControlName="departmentId">@for(d of data.departments;track d.id){<mat-option [value]="d.id">{{d.name}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>Zile anuale</mat-label><input matInput type="number" formControlName="annualLeaveDays"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Zile disponibile</mat-label><input matInput type="number" formControlName="availableLeaveDays"/></mat-form-field><mat-checkbox formControlName="active">Cont activ</mat-checkbox></form></mat-dialog-content><mat-dialog-actions align="end"><button mat-button mat-dialog-close>Renunta</button><button mat-flat-button class="save" (click)="submit()">Salveaza</button></mat-dialog-actions>`,styles:[`.grid{display:grid;grid-template-columns:1fr 1fr;gap:4px 12px;width:min(570px,78vw)}.full{grid-column:1/-1}.save{background:#0a91a6;color:white}@media(max-width:600px){.grid{grid-template-columns:1fr}.full{grid-column:auto}}`]})
export class EmployeeDialogComponent{readonly data=inject<{item?:Employee;departments:Department[]}>(MAT_DIALOG_DATA);private readonly ref=inject(MatDialogRef<EmployeeDialogComponent>);private readonly fb=inject(FormBuilder);readonly form=this.fb.nonNullable.group({name:[this.data.item?.name??'',Validators.required],email:[this.data.item?.email??'',[Validators.required,Validators.email]],password:[''],role:[this.data.item?.role??'EMPLOYEE' as Role,Validators.required],departmentId:[this.data.item?.departmentId??this.data.departments[0]?.id,Validators.required],annualLeaveDays:[this.data.item?.annualLeaveDays??21,[Validators.required,Validators.min(0)]],availableLeaveDays:[this.data.item?.availableLeaveDays??21,[Validators.required,Validators.min(0)]],active:[this.data.item?.active??true]});submit(){if(this.form.invalid){this.form.markAllAsTouched();return}this.ref.close(this.form.getRawValue())}}

@Component({selector:'app-department-dialog',imports,template:`<h2 mat-dialog-title>{{data.item?'Modifica departamentul':'Departament nou'}}</h2><mat-dialog-content><form [formGroup]="form" class="form"><mat-form-field appearance="outline"><mat-label>Denumire</mat-label><input matInput formControlName="name"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Maximum absenti simultan</mat-label><input matInput type="number" formControlName="maxAbsentEmployees"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Responsabil</mat-label><mat-select formControlName="managerId"><mat-option [value]="null">Fara responsabil</mat-option>@for(e of managers();track e.id){<mat-option [value]="e.id">{{e.name}}</mat-option>}</mat-select></mat-form-field></form></mat-dialog-content><mat-dialog-actions align="end"><button mat-button mat-dialog-close>Renunta</button><button mat-flat-button class="save" (click)="submit()">Salveaza</button></mat-dialog-actions>`,styles:[`.form{display:grid;width:min(450px,75vw)}.save{background:#0a91a6;color:white}`]})
export class DepartmentDialogComponent{readonly data=inject<{item?:Department;employees:Employee[]}>(MAT_DIALOG_DATA);private readonly ref=inject(MatDialogRef<DepartmentDialogComponent>);private readonly fb=inject(FormBuilder);readonly form=this.fb.group({name:[this.data.item?.name??'',Validators.required],managerId:[this.data.item?.managerId??null as number|null],maxAbsentEmployees:[this.data.item?.maxAbsentEmployees??1,[Validators.required,Validators.min(1)]]});managers(){return this.data.item?this.data.employees.filter(e=>(e.role==='MANAGER'||e.role==='ADMIN')&&e.departmentId===this.data.item!.id):[]}submit(){if(this.form.invalid){this.form.markAllAsTouched();return}this.ref.close(this.form.getRawValue())}}

@Component({selector:'app-leave-type-dialog',imports,template:`<h2 mat-dialog-title>{{data.item?'Modifica tipul':'Tip de concediu nou'}}</h2><mat-dialog-content><form [formGroup]="form" class="form"><mat-form-field appearance="outline"><mat-label>Denumire</mat-label><input matInput formControlName="name"/></mat-form-field><mat-form-field appearance="outline"><mat-label>Cod</mat-label><input matInput formControlName="code" style="text-transform:uppercase"/></mat-form-field><mat-checkbox formControlName="requiresAttachment">Necesita document justificativ</mat-checkbox><mat-checkbox formControlName="paid">Concediu platit</mat-checkbox></form></mat-dialog-content><mat-dialog-actions align="end"><button mat-button mat-dialog-close>Renunta</button><button mat-flat-button class="save" (click)="submit()">Salveaza</button></mat-dialog-actions>`,styles:[`.form{display:grid;width:min(450px,75vw);padding-bottom:5px}.save{background:#0a91a6;color:white}`]})
export class LeaveTypeDialogComponent{readonly data=inject<{item?:LeaveType}>(MAT_DIALOG_DATA);private readonly ref=inject(MatDialogRef<LeaveTypeDialogComponent>);private readonly fb=inject(FormBuilder);readonly form=this.fb.nonNullable.group({name:[this.data.item?.name??'',Validators.required],code:[this.data.item?.code??'',Validators.required],requiresAttachment:[this.data.item?.requiresAttachment??false],paid:[this.data.item?.paid??true]});submit(){if(this.form.invalid){this.form.markAllAsTouched();return}this.ref.close(this.form.getRawValue())}}
